import type { CandidateProfile } from "@/lib/types";

export const MOCK_CANDIDATE_PROFILES: CandidateProfile[] = [
  {
    id: "startup-ai-product-engineer",
    candidateName: "Maya R.",
    title: "Founding AI Product Engineer",
    profileMatch: 88,
    archetype: "Startup AI Product Engineer",
    companyStyle: "Seed to Series B AI product startup",
    backgroundSummary: "Shipped customer-facing LLM workflows at an early AI workflow company; moved from prototype to paid usage.",
    fitAssessment: "Best current calibration anchor if speed, customer proximity, and product judgment are the real job.",
    strongestSignals: ["built user-facing LLM workflows", "strong demo velocity", "close to customers"],
    skillsetHighlights: ["LLM UX", "TypeScript", "eval loops"],
    likelyTradeoffs: ["less research pedigree", "may need stronger infra partner"],
    startupFit: "High",
    marketPressure: "Competitive",
    whyTinaSurfacedIt: "The initial ask values speed, customer contact, and practical AI product judgment."
  },
  {
    id: "frontier-ai-lab-engineer",
    candidateName: "Ethan K.",
    title: "AI Engineer, Frontier Systems",
    profileMatch: 72,
    archetype: "Frontier AI Lab Engineer",
    companyStyle: "Frontier lab or research-heavy AI platform",
    backgroundSummary: "Deep model and eval exposure from research-heavy AI environments; less evidence of founder-stage product shipping.",
    fitAssessment: "Useful if model depth is mission-critical; risky if the company mostly needs product velocity.",
    strongestSignals: ["model intuition", "eval design", "credible frontier AI exposure"],
    skillsetHighlights: ["model evals", "Python", "research systems"],
    likelyTradeoffs: ["narrower market", "higher comp pressure", "may prefer research over messy product work"],
    startupFit: "Medium",
    marketPressure: "High",
    whyTinaSurfacedIt: "The founder mentioned OpenAI or Anthropic experience as a possible signal."
  },
  {
    id: "ml-infrastructure-engineer",
    candidateName: "Nina S.",
    title: "Senior ML Infrastructure Engineer",
    profileMatch: 79,
    archetype: "ML Infrastructure Engineer",
    companyStyle: "AI infra, data platform, or model-serving team",
    backgroundSummary: "Built model-serving and observability foundations in production AI systems.",
    fitAssessment: "Strong if reliability and scale are the bottleneck; weaker if discovery and customer pull are central.",
    strongestSignals: ["production ML systems", "observability", "data and eval loops"],
    skillsetHighlights: ["model serving", "data infra", "observability"],
    likelyTradeoffs: ["less customer-facing", "may not own product discovery"],
    startupFit: "Medium-high",
    marketPressure: "Competitive",
    whyTinaSurfacedIt: "This lane tests whether the real pain is reliability, scale, and model operations."
  },
  {
    id: "applied-ai-generalist",
    candidateName: "Leo C.",
    title: "Applied AI Generalist",
    profileMatch: 84,
    archetype: "Applied AI Generalist",
    companyStyle: "Early AI tool, automation company, or founder-led product team",
    backgroundSummary: "Broad builder who has connected product, data, prompts, and backend in ambiguous zero-to-one settings.",
    fitAssessment: "High-upside calibration lane if the role is still broad and the company needs learning speed.",
    strongestSignals: ["turns vague ideas into working product", "full-stack range", "comfortable with ambiguity"],
    skillsetHighlights: ["full-stack", "prompt systems", "customer iteration"],
    likelyTradeoffs: ["less specialist depth", "technical ceiling needs validation"],
    startupFit: "Very high",
    marketPressure: "Manageable",
    whyTinaSurfacedIt: "This gives the team a broad builder lane before narrowing into specialist requirements."
  },
  {
    id: "backend-infra-ai-exposure",
    candidateName: "Priya M.",
    title: "Backend Engineer with AI Exposure",
    profileMatch: 76,
    archetype: "Backend Infra Engineer with AI exposure",
    companyStyle: "Developer tools, workflow software, or infrastructure startup",
    backgroundSummary: "Strong backend owner with adjacent AI product work and enough model fluency to build around LLMs.",
    fitAssessment: "Pragmatic lane if system quality matters more than frontier AI novelty.",
    strongestSignals: ["backend ownership", "systems quality", "enough AI fluency to build with models"],
    skillsetHighlights: ["APIs", "reliability", "LLM integration"],
    likelyTradeoffs: ["not a frontier AI expert", "may need pairing on eval strategy"],
    startupFit: "High",
    marketPressure: "Manageable",
    whyTinaSurfacedIt: "This lane preserves execution quality without making frontier lab pedigree a hard gate."
  },
  {
    id: "ai-solutions-founder-type",
    candidateName: "Owen T.",
    title: "Customer-Facing AI Builder",
    profileMatch: 81,
    archetype: "Applied AI Generalist",
    companyStyle: "Customer-facing AI solutions or technical founder background",
    backgroundSummary: "Built AI prototypes directly with customers and translated messy feedback into usable demos.",
    fitAssessment: "Strong if customer pull is a major part of the founding engineer job.",
    strongestSignals: ["customer empathy", "rapid prototyping", "can sell the work internally"],
    skillsetHighlights: ["solution design", "rapid prototyping", "customer discovery"],
    likelyTradeoffs: ["may be lighter on deep infra", "requires crisp ownership boundaries"],
    startupFit: "High",
    marketPressure: "Competitive",
    whyTinaSurfacedIt: "The request includes customer work and speed, which can matter more than pure technical pedigree."
  }
];
